config/routes.rb
Blog::Application.routes.draw do
    
    resources :posts
    

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :presence => true
  validates :content, :presence => true,
            :length => { :minimun => 5 }
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path
      else
      render action: 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#eee">

<%= link_to image_tag('logo.jpg', :size => '200x40'), '/' %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
<% @posts.each do |post| %>
<li>
<%= link_to post.title, post_path(post) %>
<%= link_to 'Edit', edit_post_path(post) %>
</li>
<% end %>
</ul>

<%= link_to 'home', posts_path %> | <%= link_to 'New', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</1h>

<%= form_for(@post) do |f| %>

<% if @post.errors.any? %>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div class="field">
  <%=f.label :title %>
  <%=f.text_field :title %>
</div>

<div class="field">
  <%= f.label :content %>
  <%= f.text_area :content, :rows => 5 %>
</div>


<% end %>
<%= link_to 'home', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>


<%= link_to 'home', posts_path %>